Fapi: Fix memory leak
tpm2-software/tpm2-tss pull request #1879
Opened 2020-10-28 12:50 UTC by AndreasFuchsSIT

Fix a memory leak if FAPI caused by free after sync return.

2020-10-28 13:02 UTC, JuergenReppSIT approved these changes

2020-10-28 14:32 UTC, JuergenReppSIT requested changes
SAFE_FREE(outPublic); 
has to be moved behind line 3392

2020-10-29 09:42 UTC, JuergenReppSIT approved these changes

2020-10-29 10:49 UTC, AndreasFuchsSIT commented
> SAFE_FREE(outPublic);
> has to be moved behind line 3392

Ok, I moved it.

2020-10-29 11:44 UTC, JuergenReppSIT approved these changes

2020-10-29 12:35 UTC, JuergenReppSIT approved these changes

2020-10-30 09:51 UTC, merged