FAPI: Perform URL encoding
tpm2-software/tpm2-tss pull request #2049
Opened 2021-03-25 14:57 UTC by mailhost

Use the libcurl API to perform url encoding.

During operations such as tss2_provisioning, the parsed EK x509 cert may hold
a reference to a CA Issuer URI that does not adhere to rfc3986
"character encoding" requirements, a.k.a percent-encoding. We need to
perform url encoding before attempting to GET the resource.

Fixes #2046

2021-03-25 15:02 UTC, williamcroberts commented
Please sign off your commit:
```bash
git commit --amend -s
git push -f mailhost
# or whatever your remote is named.
```

2021-03-25 16:02 UTC, williamcroberts commented
Somehow you ended up with 3 commits. You just want one commit. I'll clean up your history for you.

The CI is failing, becuase it appears that ubuntu18.04 version of curl is too old. 7.68.0 appears to missing the URL API:
  - https://github.com/curl/curl/commit/fb30ac5a2d63773c529c19259754e2b306ac2e2e
  
 Which I don't understand, because it shows the commit on 7.68.0 of the library:
```bash
$ git tag --contains fb30ac5a2
<snip>
curl-7_68_0
<snip>
```

But the header file:
```bash
pkg-config --cflags-only-I libcurl
-I/usr/include/x86_64-linux-gnu
```

```C
#define CURLVERSION_NOW CURLVERSION_SIXTH
```
Seems suspicious

2021-03-25 16:05 UTC, williamcroberts requested changes

2021-03-25 16:05 UTC, williamcroberts commented on src/tss2-fapi/ifapi_helpers.c
> +    CURLU *urlp = curl_url();
null check curl_url(): https://curl.se/libcurl/c/curl_url.html

2021-03-25 16:05 UTC, williamcroberts commented on src/tss2-fapi/ifapi_helpers.c
> +    res = curl_url_set(urlp, CURLUPART_URL, url, CURLU_URLENCODE);
check return value

2021-03-25 16:05 UTC, williamcroberts commented on src/tss2-fapi/ifapi_helpers.c
> +    int res = 0;
Why not just use rc?

2021-03-25 16:07 UTC, williamcroberts commented
Seems curl on ubuntu-18.04 is only 7.58... So these aren't supported. https://packages.ubuntu.com/bionic/curl

2021-03-25 16:10 UTC, AndreasFuchsSIT commented
`AC_CHECK_LIB(curl, curl_url,[AC_DEFINE([HAVE_CURL_URL],[1],[Check for curl_url()])`
and
`#ifdef HAVE_CURL_URL`
?

2021-03-25 16:24 UTC, williamcroberts commented
> `AC_CHECK_LIB(curl, curl_url,[AC_DEFINE([HAVE_CURL_URL],[1],[Check for curl_url()])`
> and
> `#ifdef HAVE_CURL_URL`
> ?

curl.pc is provided by libcurl4-gnutls-dev (or openssl or nss variants). For some reason on my system it shows curl as being version 7.68 but the package itself provides 7.58. I don't ever recall building it by scratch and messing with it.

In docker of ubuntu 18.04, it shows the right one:
```
pkg-config --modversion libcurl
7.58.0
```

Wouldn't we want to find a fix that's going to scale across all of our active build flavors here?
Dang debian and their old packages!

2021-03-25 16:26 UTC, williamcroberts commented on src/tss2-fapi/ifapi_helpers.c
> -    rc = curl_easy_setopt(curl, CURLOPT_URL, url);
Just use curl_easy_escape on URL and pass that to curl_easy_setopt.

2021-03-25 16:28 UTC, AndreasFuchsSIT commented
> Wouldn't we want to find a fix that's going to scale across all of our active build flavors here?
> Dang debian and their old packages!

I guess that would mean `url = str_replace(url, " ", "%20");` ?
There is no such function in standard-C though, right ?

2021-03-25 16:30 UTC, williamcroberts commented
Summary:
I think the right fix here is to take the URL and pass it through curl_easy_escape(). Then pass that to curl_easy_setopt(curl, CURLOPT_URL, url);

Just make sure to curl_free() the url returned from curl_easy_escape().

This is how tpm2-tools tpm2_getekcertificate.c does it for a reference:
  - https://github.com/tpm2-software/tpm2-tools/blob/master/tools/tpm2_getekcertificate.c#L179
  - https://github.com/tpm2-software/tpm2-tools/blob/master/tools/tpm2_getekcertificate.c#L239

2021-03-25 16:30 UTC, williamcroberts commented
> > Wouldn't we want to find a fix that's going to scale across all of our active build flavors here?
> > Dang debian and their old packages!
> 
> I guess that would mean `url = str_replace(url, " ", "%20");` ?
> There is no such function in standard-C though, right ?

curl_easy_escape, see my "summary" comment.

2021-04-09 18:08 UTC, williamcroberts commented
> > > Wouldn't we want to find a fix that's going to scale across all of our active build flavors here?
> > > Dang debian and their old packages!
> > 
> > 
> > I guess that would mean `url = str_replace(url, " ", "%20");` ?
> > There is no such function in standard-C though, right ?
> 
> curl_easy_escape, see my "summary" comment.

@tstruk can you make these changes using curl_easy_escape and get it staged for next and backport branches since you're working on the releases or is it too late?

2021-06-09 16:57 UTC, williamcroberts commented
Replaced by: https://github.com/tpm2-software/tpm2-tss/pull/2088

2021-06-09 16:57 UTC, closed without merging