Removed annyoying '$' sign in INSTALL.md
tpm2-software/tpm2-tss pull request #2163
Opened 2021-09-27 12:41 UTC by lap1nou

Removed annyoying '$' sign in INSTALL.md, we couldn't easily copy/paste command in the install documentation because of those sign.

2021-09-28 09:25 UTC, AndreasFuchsSIT approved these changes

2021-09-28 09:27 UTC, AndreasFuchsSIT requested changes
Could you rebase this into a single commit and add a signed-off ?

2021-09-28 17:46 UTC, lap1nou commented
Hum, I'm not really familiar with the "commit merging", should I run the "git rebase" command right ? About the sign off, that's strange I followed the instructions given by the bot but it doesn't seem to work, maybe I signed off one of the commit only.

2021-09-29 07:11 UTC, AndreasFuchsSIT commented
Some of your commits have sign-offs, some don't.
Also you have some merge-commits in there. For our project we opted to only do fast-forward-merges aka rebased commits (a bit more svn-like).

You would have to "rebase to master" or maybe even "cherry-pick" into a new branch, "rebase interactive and squash your commits into one", and "--ammend --signoff"
Those should be the google terms. Sorry but too long to explain all this here.

I guess the easiest is for you to make a new branch and redo your changes.
For beginners I also recommend using `gitg` to make commits a bit easier.

2021-12-14 16:11 UTC, closed without merging