Tpm2-tss build with VS2019 + Windows ARM64
tpm2-software/tpm2-tss pull request #2182
Opened 2021-10-22 23:28 UTC by achal1012

2022-06-14 10:46 UTC, AndreasFuchsTPM commented
First of all: Our .gitignore file is autogenerated. We don't want to add it just for Windows env. IMHO windows should be able to know which files it generates by itself quite nicely without need for a .gitignore, or am I wrong ?

Then: Are you still working on this (since this was a "draft") or have you given up ?

2022-06-14 14:23 UTC, achal1012 commented
> First of all: Our .gitignore file is autogenerated. We don't want to add it just for Windows env. IMHO windows should be able to know which files it generates by itself quite nicely without need for a .gitignore, or am I wrong ?
> 
> Then: Are you still working on this (since this was a "draft") or have you given up ?

Hi @AndreasFuchsTPM you are right; gitignore was required for our dev setup.
I have no intention to merge this in unless the authours of this repo want me to; I just created this draft PR so my teammates can look at the diff and build this for ARM64 platform. :)

2022-06-14 14:46 UTC, williamcroberts commented
I guess we could take the changes to the project files. For the gitignore you can add it to `.git/info/exclude`. Everyone who works on it can just drop it in there. This is per: https://www.atlassian.com/git/tutorials/saving-changes/gitignore#personal-git-ignore-rules

2022-06-14 14:58 UTC, achal1012 commented
> I guess we could take the changes to the project files. For the gitignore you can add it to `.git/info/exclude`. Everyone who works on it can just drop it in there. This is per: https://www.atlassian.com/git/tutorials/saving-changes/gitignore#personal-git-ignore-rules

Sure let me fix the changes and publish the pull request.

2022-10-26 14:50 UTC, williamcroberts commented
@achal1012 I took the liberty of fixing the merge conflicts since we took so long to review this again. Could you sign off your commits though to make the DCO bot happy?

2022-11-15 14:25 UTC, AndreasFuchsTPM commented
IMHO we should squash the two commits into a single one.

@achal1012 Could you provide some reference to the target platform you are using so we could setup our own testing env for this ?

2022-11-15 15:09 UTC, achal1012 commented
Hi @williamcroberts: I am unable to approve this PR as github is not letting me. And I apologize for no updates on this PR, I changed employers and lost my setup and test bench.

@AndreasFuchsTPM I tested this on Ampere platform with internal windows ARM564 build, and unfortunately I don't have access to that now.

2022-11-15 16:06 UTC, williamcroberts commented
> Hi @williamcroberts: I am unable to approve this PR as github is not letting me. 

You don't need to approve anything, You can still sign off your commits. In the Tests section for your PR you'll see a DCO thing that shows as failed, follow it's steps:
  - https://github.com/tpm2-software/tpm2-tss/pull/2182/checks?check_run_id=9119972325

> And I apologize for no updates on this PR, I changed employers and lost my setup and test bench.

We'll as long as it didn't break the normal x86-64 builds so I am fine with pulling it as is as experimental ARM64 support.

2022-11-16 20:51 UTC, williamcroberts commented
> > You don't need to approve anything, You can still sign off your commits. In the Tests section for your PR you'll see a DCO thing that shows as failed, follow it's steps:
> > 
> > * https://github.com/tpm2-software/tpm2-tss/pull/2182/checks?check_run_id=9119972325
> 
> I followed the steps and pushed the change. Can you check if its okay now?

DCO bot happy, lets let CI spin and I can pull this in for 4.0 release.

2022-11-17 11:11 UTC, AndreasFuchsTPM requested changes
AppVeyor complains that
```esys_crypto_ossl.c(11,10): fatal error : 'openssl/rand.h' file not found [C:\projects\tpm2-tss\src\tss2-esys\tss2-esys.vcxproj]```

I see that include-paths were changed for OpenSSL.
I don't know though, how to nicely handle this.

2022-11-17 11:11 UTC, AndreasFuchsTPM commented on src/tss2-esys/tss2-esys.vcxproj
> +      <AdditionalDependencies>$(OutDir)\tss2-mu.lib;$(OutDir)\tss2-sys.lib;$(OutDir)\tss2-tctildr.lib;C:\OpenSSL.1.1.1506.73\$(Platform)\$(Configuration)\lib\libcrypto.lib;%(AdditionalDependencies)</
This change apparently breaks our Appveyor-CI

2022-11-17 11:11 UTC, AndreasFuchsTPM commented on src/tss2-esys/tss2-esys.vcxproj
> +      <AdditionalDependencies>$(OutDir)\tss2-mu.lib;$(OutDir)\tss2-sys.lib;$(OutDir)\tss2-tctildr.lib;C:\OpenSSL.1.1.1506.73\$(Platform)\$(Configuration)\lib\libcrypto.lib;%(AdditionalDependencies)</
Same here

2022-11-17 11:11 UTC, AndreasFuchsTPM commented on src/tss2-esys/tss2-esys.vcxproj
> +      <AdditionalIncludeDirectories>$(SolutionDir);$(SolutionDir)\src;$(SolutionDir)\include\tss2;$(SolutionDir)\src\tss2-mu;$(SolutionDir)\src\tss2-sys;$(SolutionDir)\src\tss2-esys;C:\OpenSSL.1.1.15
And here

2022-11-17 11:11 UTC, AndreasFuchsTPM commented on src/tss2-esys/tss2-esys.vcxproj
> +      <AdditionalDependencies>$(OutDir)\tss2-mu.lib;$(OutDir)\tss2-sys.lib;$(OutDir)\tss2-tctildr.lib;C:\OpenSSL.1.1.1506.73\$(Platform)\$(Configuration)\lib\libcrypto.lib;%(AdditionalDependencies)</
and here

2022-11-17 17:55 UTC, williamcroberts commented
> AppVeyor complains that `esys_crypto_ossl.c(11,10): fatal error : 'openssl/rand.h' file not found [C:\projects\tpm2-tss\src\tss2-esys\tss2-esys.vcxproj]`
> 
> I see that include-paths were changed for OpenSSL. I don't know though, how to nicely handle this.

If it breaks appveyor we don't pull, @achal1012 if you can add your arm64 support and AppVeyor is happy thats good enough for me, but otherwise we won't be able to take this PR. I thought AppVeyor was happy at one point....

2022-11-24 00:10 UTC, achal1012 commented
> > AppVeyor complains that `esys_crypto_ossl.c(11,10): fatal error : 'openssl/rand.h' file not found [C:\projects\tpm2-tss\src\tss2-esys\tss2-esys.vcxproj]`
> > I see that include-paths were changed for OpenSSL. I don't know though, how to nicely handle this.
> 
> If it breaks appveyor we don't pull, @achal1012 if you can add your arm64 support and AppVeyor is happy thats good enough for me, but otherwise we won't be able to take this PR. I thought AppVeyor was happy at one point....

Yes, I think here we have to use a build of OpenSSL that has the ARM64 libs as well. 
```C:\OpenSSL.1.1.1506.73```
This was a hardcoded version I was using.

2022-11-24 00:11 UTC, achal1012 commented
Can we keep this PR in draft till I can find some time to work on this? Or do we need to abandon it?

2022-11-25 19:25 UTC, williamcroberts commented
> Can we keep this PR in draft till I can find some time to work on this? Or do we need to abandon it?

We can just leave it open

2025-09-03 14:32 UTC, closed without merging