fapi: Fix json encoding of policies with complex TPM2Bs.
tpm2-software/tpm2-tss pull request #2396
Opened 2022-07-23 07:41 UTC by JuergenReppSIT

The json spec states that complex TPM2Bs do not have a JSON representation.
Currently it's possible to use the the representation of a complex TPM2B
in policy authorize nv, in policy duplication select, policy template.
The usage of the embedded TPMT or TPMS JSON representation, as required
by the spec, can't be used.
To achieve backward compatibility with existing key stores both cases now
can be used.
Policy duplication select is specified with TPMT_PUBLIC for newParentPublic
while the implementation uses TPM2B_PUBLIC. Now TPMT_PUBLIC is used but
also here the JSON representation of the TPM2B_PUBLIC can be deserialized.
Addresses #2383.

Signed-off-by: Juergen Repp <juergen_repp@web.de>

2022-07-25 18:08 UTC, williamcroberts requested changes

2022-07-25 18:08 UTC, williamcroberts commented on src/tss2-fapi/ifapi_json_deserialize.h
> + * TPM2B, and of the embedde structure will be allowed.
spelling: "embedde" to "embedded".

2022-07-25 18:09 UTC, williamcroberts commented
> The usage of the embedded TPMT or TPMS JSON representation, as required
by the spec, can't be used.

Why?

2022-07-26 06:14 UTC, JuergenReppSIT commented
> > The usage of the embedded TPMT or TPMS JSON representation, as required
> > by the spec, can't be used.
> 
> Why?
In the current version you will get an error if the JSON representation of the TPMS or TPMT structure is used instead of the complex TPM2B.

2022-08-02 16:08 UTC, AndreasFuchsTPM commented
I guess an example JSON of current behavior and expected would be nice for understanding.
Also I guess that this case is currently not covered by an integration test, so we might need one...

2022-08-03 14:17 UTC, JuergenReppSIT commented
> I guess an example JSON of current behavior and expected would be nice for understanding. Also I guess that this case is currently not covered by an integration test, so we might need one...

I have added integration tests and a unit test to cover these cases.

2022-08-03 19:10 UTC, williamcroberts approved these changes

2022-08-04 12:17 UTC, merged