FAPI: Allow keyedhash keys in PolicySigned.
tpm2-software/tpm2-tss pull request #2475
Opened 2022-11-09 18:52 UTC by JuergenReppSIT

* The attribute sign is now possible for sealed objects, to enable the usage of the sealed object as HMAC key in policy signed.
* Instead of the base64 encoded public key now the name of the sealed object will be passed (base64 encoded) to the signature callback
* An integration test is added.

Fixes #2445

Signed-off-by: Juergen Repp <juergen_repp@web.de>

2022-11-11 14:40 UTC, williamcroberts approved these changes

2022-11-11 14:40 UTC, williamcroberts commented on src/tss2-fapi/ifapi_policy_callbacks.c
> +        statecase(cb_ctx->cb_state, POL_CB_READ_OBJECT);
put this hunk on it's own patch

2022-11-11 14:41 UTC, williamcroberts requested changes
just split that hunk out... I was forced by GH to put a comment here... so let me say split that hunk out for the fiftieth time like a jerk :-p

2022-11-11 15:03 UTC, JuergenReppSIT commented
> just split that hunk out... I was forced by GH to put a comment here... so let me say split that hunk out for the fiftieth time like a jerk :-p

@williamcroberts Should I create a second commit, just with the fix of indentation? Would that solve your problem with gh?

2022-11-14 08:37 UTC, JuergenReppSIT commented
@williamcroberts I have added a second commit. Can the PR be merged now?

2022-11-14 14:18 UTC, williamcroberts approved these changes

2022-11-14 14:19 UTC, merged