FAPI: Fix compiler warnings
tpm2-software/tpm2-tss pull request #2789
Opened 2024-03-18 02:51 UTC by jasonbking

On some platforms, compiler warnings are generated due to not include <strings.h> (note plural) when using index(3) as well as not utilizing the return value to BIO_flush().

2024-03-21 14:01 UTC, AndreasFuchsTPM requested changes
Now that we have the CI up and running again...
@jasonbking Would you mind rebasing to latest master and force-pushing ?

2024-04-09 07:23 UTC, AndreasFuchsTPM requested changes
This somehow seems to mess up the BSD build.
We see all failures now for FAPI.
But I'm puzzled, as to why this is...

2024-04-09 13:06 UTC, JuergenReppSIT commented
@AndreasFuchsTPM after starting the rerun everything worked. Also in my local BSD vm I could run the test several times without problems.

2024-04-10 07:32 UTC, AndreasFuchsTPM approved these changes

2024-04-10 07:33 UTC, merged